modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="passiveregen"
version="1.1.2+1.16.5-forge"
displayName="Passive Health Regen"
description='''
Configurable passive out-of-combat regeneration without a potion effect.
'''

[[dependencies.passiveregen]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.passiveregen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
