modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="passiveregen"
version="1.3.0+1.20.1-neoforge"
displayName="Passive Health Regen"
description='''
Configurable passive out-of-combat regeneration without a potion effect.
'''

[[dependencies.passiveregen]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.passiveregen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
